# Render.com 배포용 설정
services:
  - type: web
    name: survey-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: True
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1,survey-backend-dgiy.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: survey-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: "https://survey-new-wheat.vercel.app,https://survey-zeta-seven.vercel.app,https://survey-amz9fv00u-commaeng09s-projects.vercel.app"

databases:
  - name: survey-db
    databaseName: survey
    user: survey_user
    plan: free
    region: oregon
