# Render.com 배포용 설정
services:
  - type: web
    name: survey-backend
    env: python
    plan: free
    region: oregon
    buildCommand: "cd backend && pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "cd backend && python manage.py migrate && gunicorn survey_project.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: survey-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: "https://survey-zeta-seven.vercel.app,https://survey-amz9fv00u-commaeng09s-projects.vercel.app"

  - type: pserv
    name: survey-db
    plan: free
    region: oregon
