# Generated by Django 4.2.7 on 2025-07-27 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('active', '진행중'), ('completed', '완료'), ('scheduled', '예약됨')], default='draft', max_length=20, verbose_name='상태')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='예약일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('response_count', models.IntegerField(default=0, verbose_name='응답수')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '설문조사',
                'verbose_name_plural': '설문조사들',
                'db_table': 'surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respondent_email', models.EmailField(blank=True, max_length=254, verbose_name='응답자 이메일')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='제출일시')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey', verbose_name='설문조사')),
            ],
            options={
                'verbose_name': '응답',
                'verbose_name_plural': '응답들',
                'db_table': 'responses',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500, verbose_name='질문')),
                ('description', models.TextField(blank=True, verbose_name='질문 설명')),
                ('type', models.CharField(choices=[('text', '단답형'), ('textarea', '장문형'), ('radio', '객관식(단일선택)'), ('checkbox', '객관식(다중선택)'), ('dropdown', '드롭다운'), ('rating', '평점'), ('date', '날짜'), ('time', '시간'), ('email', '이메일'), ('phone', '전화번호')], max_length=20, verbose_name='질문 유형')),
                ('required', models.BooleanField(default=False, verbose_name='필수 여부')),
                ('order', models.IntegerField(verbose_name='순서')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='선택지')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey', verbose_name='설문조사')),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '질문들',
                'db_table': 'questions',
                'ordering': ['order'],
                'unique_together': {('survey', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_answer', models.TextField(blank=True, verbose_name='텍스트 답변')),
                ('choice_answers', models.JSONField(blank=True, default=list, verbose_name='선택 답변')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.question', verbose_name='질문')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.response', verbose_name='응답')),
            ],
            options={
                'verbose_name': '답변',
                'verbose_name_plural': '답변들',
                'db_table': 'answers',
                'unique_together': {('response', 'question')},
            },
        ),
    ]
